### ISSUE TITLE
Commit info not shown in "Activity" tab when running `pulumi up` from CI/CD

### ISSUE THREAD

**Issue by wtfzambo** [pulumi/service-requests#156] opened 2023-01-03 14:51 UTC
I have setup a CI/CD pipeline using AWS Code Build and Code Pipeline to essentially run `pulumi up` when new changes are pushed to my pulumi project repo.

When the pipeline runs and the update is successful, the "Activity" tab in the Pulumi UI doesn't show the commit info. However, it shows them when I run `pulumi up` or `pulumi preview` locally.

## Expected behavior
Commit info is displayed under "Activity" when `pulumi up` or `preview` is ran within a CI/CD pipeline (AWS Code Build, Code Pipeline)

## Actual behavior
Commit info is not displayed under "Activity" when `pulumi up` or `preview` is ran within a CI/CD pipeline, however, it is displayed when running `pulumi up` or `preview` locally. See screenshots:
- Local: 
  - preview
![image](https://user-images.githubusercontent.com/47462792/210380085-046257ad-e3fa-4cc1-896a-7ab320fd6c9f.png)

- From CI/CD: 
  - preview
![image](https://user-images.githubusercontent.com/47462792/210380542-6db94fe5-3df4-4962-a5cb-4f678242737b.png)
  - update
![image](https://user-images.githubusercontent.com/47462792/210380599-6a837e0f-cf21-4277-9bc0-a27cc619ac23.png)

## Steps to reproduce

Hard to provide a perfect replica because there are a lot of moving pieces, I'll try my best.

1. Have a pulumi project in some github repo with Pulumi service as backend
2. Setup AWS codebuild / pipeline to run `pulumi up` when changes are pushed to the repo (links to dockerfile, buildspec.yaml and other scripts below)
3. Make a local change, commit but don't push and run `pulumi preview` locally -> Check "Activity" tab
4. `git push` the changes to origin -> pipeline should trigger -> Check "Activity" tab

[Gist with `Dockerfile`, `buildspec.yaml` and `.sh` scripts](https://gist.github.com/wtfzambo/9d00705c0997cb56bdeabfadd71d466f)

## Context (Environment)
The issue affects me when using Pulumi service as backend because the goal is to manage the project through a CI/CD pipeline, and it would be very useful to see commit info when the stack gets updated.

## Affected feature
Not sure what to specify here.

**Comment by EvanBoyle** [comment] 2023-01-03 15:56
From your gist it looks like `git` is present on the container image. Can you verify the output of `git status` run from within `update_pulumi_stack.sh`?

This information does depend on the git enlistment being present at the time the preview is run.

**Comment by wtfzambo** [comment] 2023-01-04 08:44
@EvanBoyle you found the culprit of the cause, this is the output message:
```
fatal: not a git repository (or any parent up to mount point /codebuild)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
```

**Comment by EvanBoyle** [comment] 2023-01-04 23:15
Thanks for confirming @wtfzambo - I'm going to close this out as this is behaving as designed. You'll need to ensure there is a valid git enlistment for this to work as expected.

**Closed by EvanBoyle** 2023-01-04 23:15 UTC
Labels: kind/question, resolution/by-design

**Comment by wtfzambo** [comment] 2023-01-05 10:47
Yes, I confirm that one needs to select full repository replication in Codebuild to have also the .git folder copied. Thanks for helping me debug this!
