### ISSUE TITLE
improve performance of stack search on projects page

### ISSUE THREAD

**Issue by susanev** [pulumi/service-requests#103] opened 2022-09-16 01:55 UTC
the stack search is unusable in projects with a large number of stacks

here is a recent quote from a user
>We have a lot of stacks in our company and the search functionality is almost unusable and incredibly slow. Taking +2 minutes at times each time I even type a letter. Any improvement in the listing of searching of stacks where a company has a large number would be a huge improvement.

**Comment by EvanBoyle** [comment] 2023-02-06 17:08
closing as duplicate of https://github.com/pulumi/service-requests/issues/56

**Closed by EvanBoyle** 2023-02-06 17:08 UTC
Labels: kind/enhancement, impact/usability, resolution/duplicate, impact/performance
