### ISSUE TITLE
update-description-container contains message of the previous commit 

### ISSUE THREAD

**Issue by hamerlinski** [pulumi/service-requests#194] opened 2023-03-10 17:28 UTC
# update-description-container contains message of the previous commit

<img width="1419" alt="image" src="https://user-images.githubusercontent.com/115890980/224382356-c1763e1e-c5e5-40c2-927d-75afe6c5a4d1.png">

I've modified the Pulumi code of the resource and run `pulumi up` and applied changes. In the https://app.pulumi.com/ in the stack's page `update-description-container` (area marked with #FA3D63 colour) shows message of commit which was HEAD of the branch I was using but it does not relate to the change it self completely. What are the reasons behind this decision? Should I first run preview, then commit code and apply changes after that? This doesn't seem right. In my opinion it's misleading.
## Expected behavior
`div` with the `update-description-container` class should show a meaningful message rather than the last commit message.

## Current behavior
Last commit message is displayed.

## Steps to reproduce

1. Go to any git repository with Pulumi stack.
2. Run `pulumi up`
3. Go to the webpage of the stack you used.
4. Check desc. of the activity.

## Context (Environment)
It's misleading.

## Affected feature
It affects transparency and accessibility.

Thanks, Jakub

**Comment by susanev** [comment] 2023-03-11 02:01
@hamerlinski currently, the way it works is you need to commit ahead of running pulumi up if you want it to reference the correct commit. ideally, you should be committing to a branch, not main.

will leave this open though, as i believe also the intention of your issue is to comment on the usability of the way this feature works. will leave it to others to speak to that part of it.

**Comment by EvanBoyle** [comment] 2023-03-13 15:28
By default we do show the commit message. You can provide a custom update message by running `pulumi up --message "your message here"`.

Closing this, as this behavior is by design.

**Closed by EvanBoyle** 2023-03-13 15:28 UTC
Labels: impact/usability, kind/question, resolution/by-design, needs-triage, customer/feedback

**Comment by hamerlinski** [comment] 2023-03-13 20:11
Thanks for the answer ☺️
